draft: feat(standard-validator): Add standard schema validation
honojs/middleware pull request #887
Opened 2024-12-13 20:29 UTC by muningis

Group of different Schema Validation libraries authors has agreed on a standard schema, so other libraries, don't have even to care what validation library you're using, as typings and output _must_ match spec.

This PR has initial implementation passing tests taken from zod-validation. For now, `type verify` has been removed, but once it's back I will move it out of draft.

2025-01-15 09:00 UTC, EdamAme-x commented
great!!

2025-01-15 09:51 UTC, yusukebe commented
Hi @muningis 

This is awesome! The code below actually works!

```ts
import { Hono } from 'hono'
import { sValidator } from '@hono/standard-validator'
import { type } from 'arktype'
import * as v from 'valibot'
import { z } from 'zod'

const aSchema = type({
  agent: 'string',
})

const vSchema = v.object({
  slag: v.string(),
})

const zSchema = z.object({
  name: z.string(),
})

const app = new Hono()

app.get(
  '/:slag',
  sValidator('header', aSchema),
  sValidator('param', vSchema),
  sValidator('query', zSchema),
  (c) => {
    const headerValue = c.req.valid('header')
    const paramValue = c.req.valid('param')
    const queryValue = c.req.valid('query')
    return c.json({ headerValue, paramValue, queryValue })
  }
)

const res = await app.request('/foo?name=foo', {
  headers: {
    agent: 'foo',
  },
})

console.log(await res.json())

/**
{
  headerValue: {
    agent: "foo",
  },
  paramValue: {
    slag: "foo",
  },
  queryValue: {
    name: "foo",
  },
}
 */
```

I'll review this. First, can you add the CI like this: https://github.com/honojs/middleware/blob/main/.github/workflows/ci-hello.yml

2025-01-15 09:56 UTC, yusukebe commented on packages/standard-validator/test/__schemas__/valibot.ts
> +import { object, string, number, optional, enum_, pipe, unknown, transform, union, const, picklist } from 'valibot'
`union` and `const` are unnecessary.

```diff
diff --git a/packages/standard-validator/test/__schemas__/valibot.ts b/packages/standard-validator/test/__schemas__/valibot.ts
index 58d83fa..6bd2812 100644
--- a/packages/standard-validator/test/__schemas__/valibot.ts
+++ b/packages/standard-validator/test/__schemas__/valibot.ts
@@ -1,4 +1,4 @@
-import { object, string, number, optional, enum_, pipe, unknown, transform, union, const, picklist } from 'valibot'
+import { object, string, number, optional, pipe, unknown, transform, picklist } from 'valibot'

 const personJSONSchema = object({
   name: string(),
```

2025-01-15 09:56 UTC, yusukebe commented on packages/standard-validator/package.cjs.json
Are the files below necessary?

* `package.cjs.json`
* `tsconfig.cjs.json`
* `tsconfig.esm.json`

`tsup` can build both cjs and esm properly.

2025-01-15 09:56 UTC, muningis commented
Hy! Sure, will do it later today once I'm back from work.

2025-01-15 13:55 UTC, yusukebe commented
Hey @fabian-hiller ! Can you review this?

2025-01-15 14:00 UTC, fabian-hiller commented
Yes, I will review it later. Make sure to add Hono to the Standard Schema ecosystem list once this is merged. 😎

2025-01-15 16:08 UTC, muningis commented on packages/standard-validator/test/__schemas__/valibot.ts
> +import { object, string, number, optional, enum_, pipe, unknown, transform, union, const, picklist } from 'valibot'
Adjusted.

2025-01-15 16:08 UTC, muningis commented on packages/standard-validator/package.cjs.json
Indeed. Leftover from when I initially used vite.

2025-01-15 22:35 UTC, fabian-hiller requested changes
Once Standard Schema is accepted by the JS community, Hono could try to implement it natively to remove the adapter altogether.

2025-01-15 22:35 UTC, fabian-hiller commented on .changeset/modern-bugs-search.md
> +Initial implementation for standar schema support
Typo at "standar" and I recommend to capitalize Standard Schema (but both is not too important)

2025-01-15 22:35 UTC, fabian-hiller commented on packages/standard-validator/README.md
> +import { sValidator } from '@hono/standard-schema-validator'
I think there is a mismatch in package names. Here `@hono/standard-schema-validator` is used but in the package.json it is named `@hono/standard-validator`.

2025-01-15 22:35 UTC, fabian-hiller commented on packages/standard-validator/package.json
> +  "version": "0.0.0",
You may want to do this later, but this should probably be bumped to `0.1.0`.

2025-01-15 22:35 UTC, fabian-hiller commented on packages/standard-validator/package.json
> +    "@standard-schema/spec": "1.0.0-beta.4",
Please use the latest RC version of the spec.

2025-01-15 22:35 UTC, fabian-hiller commented on packages/standard-validator/package.json
> +    "@standard-schema/utils": "0.3.0",
We are not sure yet if we will keep the `utils` package. Feel free to give us feedback in the long run to help us make a better decision.

2025-01-15 22:35 UTC, fabian-hiller commented on packages/standard-validator/src/index.ts
> +    if (target === 'header' && isStandardSchemaValidator(schema) && schema['~standard'].types) {
`schema['~standard'].types` is always `undefined` at runtime because we just store type information here. This implementation should probably be changed or removed.

2025-01-15 22:35 UTC, fabian-hiller commented on packages/standard-validator/src/index.ts
> +    return result.value as StandardSchemaV1.InferOutput<Schema>
Is type casting necessary here? `result.value` should already be typed after we know `result.issues` is `undefined`.

2025-01-15 22:45 UTC, fabian-hiller commented on packages/standard-validator/package.json
> +    "@standard-schema/spec": "1.0.0-beta.4",
And I would probably add it as a direct dependency and not as under `peerDependencies` and `devDependencies`.

2025-01-16 03:20 UTC, yusukebe commented on .github/workflows/ci-standard-validator.yml
> +          node-version: 18.x
Please replace `18.x` with `20.x`? Some other CI uses `18.x`, but currently `20.x` is better.

2025-01-16 03:20 UTC, yusukebe commented on packages/standard-validator/package.json
> +  "version": "0.0.0",
This `0.0.0` is okay since the Changesets will bump the version automatically!

2025-01-16 07:11 UTC, muningis commented on packages/standard-validator/package.json
> +    "@standard-schema/spec": "1.0.0-beta.4",
@yusukebe WDYT? For example, we have same with other validators, such as zod or valibot.

2025-01-16 08:51 UTC, muningis commented on packages/standard-validator/src/index.ts
> +    if (target === 'header' && isStandardSchemaValidator(schema) && schema['~standard'].types) {
Hm, I guess tests has issues then if they passed. Will have to adjust. 
And it will have to be changed, as we need to re-write keys of a schema/shape, so that all keys are lower-cased.

2025-01-16 08:54 UTC, muningis commented on packages/standard-validator/src/index.ts
> +    return result.value as StandardSchemaV1.InferOutput<Schema>
Unfortunately, yeah. (Same is required by zod and valibot validators).

It comes down to some type issues coming from `hono/validator` (haven't had chance to dive in yet).

2025-01-16 16:11 UTC, fabian-hiller commented on packages/standard-validator/package.json
> +    "@standard-schema/spec": "1.0.0-beta.4",
To clarify, when using the Hono Valibot adapter, you already have Valibot installed, otherwise the adapter makes no sense. With Standard Schema this is different, as any library that supports the spec is compatible. Users will never install Standard Schema themselves. Note that Standard Schema contains only types and no runtime code.

2025-01-16 16:13 UTC, fabian-hiller commented on packages/standard-validator/package.json
> +    "@standard-schema/spec": "1.0.0-beta.4",
I have heard that dev dependencies may not be installed when a package is installed. So adding it as a dependency might be safer. But feel free to investigate and report back.

2025-01-16 16:17 UTC, fabian-hiller commented on packages/standard-validator/src/index.ts
> +    if (target === 'header' && isStandardSchemaValidator(schema) && schema['~standard'].types) {
This is not possible. Standard Schema does not contain an AST-like structure. Why is it necessary to rewrite the keys? Shouldn't users take care of this when writing the schema?

2025-01-17 10:11 UTC, yusukebe commented on packages/standard-validator/package.json
> +    "@standard-schema/spec": "1.0.0-beta.4",
@muningis 

I think you should add `@standard-schema/spec` as a direct dependency, as @fabian-hiller pointed out. It is used in `packages/standard-validator/src/index.ts`, so it's natural to do it.

2025-02-01 08:40 UTC, muningis commented on packages/standard-validator/src/index.ts
> +    if (target === 'header' && isStandardSchemaValidator(schema) && schema['~standard'].types) {
Hm, looks like my tests ain't correct. Other validators at the moment, rewrites headers to make them lowercase. @yusukebe WDYT, should we perhaps just expect users to write headers in lowercase in validation?

2025-02-01 10:21 UTC, yusukebe commented on packages/standard-validator/src/index.ts
> +    if (target === 'header' && isStandardSchemaValidator(schema) && schema['~standard'].types) {
@muningis 

I think you already know that the header keys are always lowercase, so it should have a map of actual keys and lower keys. This is introduced in #860

If creating the map with Standard Schema is challenging, we should expect users to write them in lowercase. This is a problem with the specification that `Headers` always keep the keys in lowercase, and we Hono-side don't need to force implement it. I think it would be enough to inform users to write the keys for validation in lowercase in the documentation.

2025-02-02 08:31 UTC, muningis commented on packages/standard-validator/src/index.ts
> +    if (target === 'header' && isStandardSchemaValidator(schema) && schema['~standard'].types) {
Upon further inspection:
1. Nor valibot nor arktype validators handles lower-casing headers.
2. From short glance, with arktype that wouldn't even be possible, as they create a function for validation.

I will drop this, and update readme to contain info.

2025-02-02 13:00 UTC, yusukebe commented on packages/standard-validator/src/index.ts
> +    if (target === 'header' && isStandardSchemaValidator(schema) && schema['~standard'].types) {
@muningis 

Thank you! Let's go with that.

2025-02-02 13:01 UTC, yusukebe approved these changes
LGTM!

2025-02-02 13:02 UTC, yusukebe commented
Hey @fabian-hiller. This looks good to me.  Can you approve this?

2025-02-02 13:37 UTC, yusukebe commented on packages/standard-validator/package.json
> +    "test": "tsc --noEmit && vitest --run",
I added the `tsc` command to test TypeScript types.

2025-02-02 13:37 UTC, yusukebe commented on packages/standard-validator/tsconfig.json
> +    "test/**/*.ts"
To test TypeScript types, you need to add this line.

2025-02-02 13:39 UTC, yusukebe commented on packages/node-ws/package.json
It was accidentally updated by `yarn` command, but I left it changed.

2025-02-03 04:22 UTC, fabian-hiller reviewed
Rest LGTM

2025-02-03 04:22 UTC, fabian-hiller commented on packages/standard-validator/src/index.ts
> +  hook?: Hook<StandardSchemaV1.InferOutput<Schema>, E, P, Target>
Should this be `Hook<Schema, E, P, Target>` instead? At least the Valibot validator middleware implementation is using the schema object and not its output.

2025-02-03 04:22 UTC, fabian-hiller commented on packages/standard-validator/src/index.ts
> +      return c.json({ data: value, error: result.issues, success: false }, 400)
This is probably not a problem in this implementation, but the Valibot validator middleware uses `output` instead of `data` for the output value. Could it be that the Valibot implementation should be updated?

2025-02-05 15:30 UTC, muningis commented on packages/standard-validator/src/index.ts
> +  hook?: Hook<StandardSchemaV1.InferOutput<Schema>, E, P, Target>
Valibot and Zod has different `Hook` implementation, this one is based on Zod.

2025-02-05 15:31 UTC, muningis commented on packages/standard-validator/src/index.ts
> +      return c.json({ data: value, error: result.issues, success: false }, 400)
Hm. Does valibot transform values if it fails to validate? Personally, I think, ideally, we should return whatever was passed, before transformations and defaults, in case of failed validation.

2025-02-05 15:34 UTC, fabian-hiller commented on packages/standard-validator/src/index.ts
> +  hook?: Hook<StandardSchemaV1.InferOutput<Schema>, E, P, Target>
@yusukebe should this be uniformed?

2025-02-05 15:37 UTC, fabian-hiller commented on packages/standard-validator/src/index.ts
> +      return c.json({ data: value, error: result.issues, success: false }, 400)
Yes, Valibot always provides an output that can contain transformations when using `safeParse` or `safeParseAsync`. I have no opinion on the implementation. I just noticed it.

2025-02-05 16:13 UTC, muningis commented on packages/standard-validator/src/index.ts
> +      return c.json({ data: value, error: result.issues, success: false }, 400)
Working with original data IMO has slightly more better handling if there’s something you need to do what’s not available/possible with schema and/or want to use it for observability. Would be nice to hear what @yusukebe has to say on this.

2025-02-06 09:30 UTC, yusukebe commented on packages/standard-validator/src/index.ts
> +  hook?: Hook<StandardSchemaV1.InferOutput<Schema>, E, P, Target>
> @yusukebe should this be uniformed?

It's better to unify the implementation. Following Zod Validator is good. The current implementation in this PR is okay, but we should change the implementation of the Valibot Validator.

2025-02-06 12:02 UTC, muningis commented
Anything else we should do, or this is good to go?

2025-02-06 12:37 UTC, yusukebe commented
This is good! Let's land it.

@muningis Thank you for the great work. Standardizing the schema libs for the validator will be a big thing for Hono and the TS/JS ecosystem!

@fabian-hiller Thank you for the review!

2025-02-06 12:38 UTC, merged

2025-02-09 19:38 UTC, Eghizio commented
Does it work with OpenAPI like [@hono/zod-openapi](https://hono.dev/examples/zod-openapi) or is it planned to?

2025-02-10 21:15 UTC, muningis commented
@Eghizio - `@hono/zod-openapi` depeneds on `@asteasolutions/zod-to-openapi`. 

From my understanding, `@asteasolutions/zod-to-openapi` relies on internals of zod (which differs from Valibot, Arktype or Effect Schema). What they have in common, is output and typings of that. Since this supports zod, it should be fine with `@hono/zod-openapi` when using just zod.

2025-02-11 00:19 UTC, Eghizio commented
Thanks @muningis 🙇 
It would be amazing to have all of the standard schema compliant validators allow for generating Open API spec & Swagger out of the box in Hono ✨